------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
YOU CAN'T REPLICATE ENTIRE LINKS PASTE HERE, BUT YOU CAN USE THE BASIC CONCEPTS EVERYWHERE THEY USED.
------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------
Templates
--------------------------------
https://www.free-css.com/
https://htmlcodex.com/
https://templatemo.com/

------------------------
CHEATSHEET
------------------------
https://overapi.com/
https://andreasbm.github.io/web-skills/
https://www.w3docs.com/
https://www.100daysofcode.com/ 
https://devdocs.io/ 

--------------------------------
Personal Portfolio Link
--------------------------------
https://damian.drygiel.com/
https://github.com/LakshmiNarayaanan?tab=overview&from=2023-12-01&to=2023-12-25 - Github Readme 

---------------------------------
Company Page Link
---------------------------------


------------------------------
Specific Section/Feature
------------------------------


------------------------------
View Page Source
------------------------------
https://www.view-page-source.com/

------------------------
Medium Blogs
------------------------
https://webcache.googleusercontent.com/search?q=cache:https://javascript.plainenglish.io/use-chrome-devtools-like-a-senior-frontend-developer-97ad3ee47647&sca_esv=590835004&strip=1&vwsrc=0

